# Author: Janusz Lewandowski <lew21@xtreeme.org>
# Contributor: David McFarland <corngood@gmail.com>
# Maintainer: Andrew Shark <ashark @at@ linuxcomp.ru>
# Contributor: Kevin Macey <image28@slingshot.co.nz>
# Autogenerated from AMD's Packages file

major=20.20
minor=1098277 

#pkgbase=amdgpu-pro-installer
pkgname=amdgpu-pro
pkgver=${major}_${minor}
pkgrel=1
arch=('x86_64')
url=https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-20-20-unified
license=('custom: multiple')
groups=('Radeon_Software_for_Linux')
makedepends=('wget')
DLAGENTS='https::/usr/bin/wget --referer https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-20-20-unified -N %u'
source=(https://drivers.amd.com/drivers/linux/amdgpu-pro-${major}-${minor}-ubuntu-20.04.tar.xz)
sha256sums=(8c08a8e3b2fc422e94a9b2226e015cfc40606b5e2613c483f9638874ccbfb312)

# Extract all files at once ( quicker, easier to maintain )
extract-all() {
	local current="`pwd`"	
	rm -rf amdgpu-pro 
	mkdir -p amdgpu-pro
	cd amdgpu-pro
	for d in `ls $current/amdgpu-pro-${major}-${minor}-ubuntu-20.04/*.deb`
	do
		ar x "$d"
		tar -C $current/../pkg/amdgpu-pro -xf data.tar.xz	
	done
	cd $current
}

package() {
    pkgdesc="AMDGPU-PRO Drivers"
    license=('MIT')
    arch=('any')
	extract-all
	mv ${pkgdir}/lib ${pkgdir}/usr/lib/
	find ${pkgdir} -type d -empty -delete
}
